[package]
name = "lgol"
version = "1.0.0"
authors = ["maaxleq <maxenceleq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
termion = "*"
ctrlc = "3.2.0"
